/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHREE
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.AbstractAction;
import javax.swing.Action;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class NewTable extends javax.swing.JFrame implements ActionListener {
    ArrayList<String> list;

    /** Creates new form NewTable */
    public NewTable() {
        initComponents();
    }

    public void addSqlDataToTable(String teamName) {
        try {
            DefaultTableModel tblModel1 = (DefaultTableModel) jTable1.getModel();
            DefaultTableModel tblModel2 = (DefaultTableModel) jTable2.getModel();
            tblModel1.setRowCount(0);
            tblModel2.setRowCount(0);

            System.out.println("Hey the team name passed here is " + teamName);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?" +
                    "user=root&password=rohitjha");
            Statement st1 = conn.createStatement();
            String query1 = "SELECT * FROM " + teamName;
            ResultSet rs1 = st1.executeQuery(query1);

            // for batsman

            while (rs1.next()) {
                String srNo = String.valueOf(rs1.getInt("SrNo"));
                String batsName = rs1.getString("BatsmanName");
                String runs = String.valueOf(rs1.getInt("Runs"));
                String balls = String.valueOf(rs1.getInt("Balls"));
                String strikeRate = rs1.getString("StrikeRate");

                String tbData[] = { srNo, batsName, runs, balls, strikeRate };
                // DefaultTableModel tblModel1 = (DefaultTableModel)jTable1.getModel();
                tblModel1.addRow(tbData);
            }
            rs1.close();
            st1.close();

            Statement st2 = conn.createStatement();
            String newName = teamName.replace("t1", "t2");

            String query2 = "SELECT * FROM " + newName;
            ResultSet rs2 = st2.executeQuery(query2);
            // for bowlers

            while (rs2.next()) {
                String id = String.valueOf(rs2.getInt("SrNo"));
                String bowlerName = rs2.getString("BowlerName");
                String balls = String.valueOf(rs2.getInt("Balls"));
                String wickets = String.valueOf(rs2.getInt("Wickets"));
                String runs = String.valueOf(rs2.getInt("Runs"));
                String economy = rs2.getString("Economy");
                String extras = String.valueOf(rs2.getInt("Extras"));

                String tbData[] = { id, bowlerName, balls, wickets, runs, economy, extras };
                // DefaultTableModel tblModel2 = (DefaultTableModel)jTable2.getModel();
                tblModel2.addRow(tbData);
            }
            rs2.close();
            st2.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "SrNo", "BatsmanName", "Runs", "Balls", "StrikeRate"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "SrNo", "BowlerName", "Balls", "Wickets", "Runs", "Economy", "Extras"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jScrollPane2.setViewportView(jTable2);
        list = new ArrayList<>();

        String query = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'javaproject';";
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?" +
                    "user=root&password=rohitjha");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                if (!(rs.getString("TABLE_NAME").equals("playerdetails"))) {
                    list.add(rs.getString("TABLE_NAME"));
                }
            }

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        String str[] = new String[list.size()];

        // System.out.println(list);
        int j = 0;
        for (int i = 0; i < list.size(); i += 2) {
            str[j] = list.get(i);
            j++;
        }

        String strJ[] = new String[(str.length) / 2];
        for (int index = 0; index < strJ.length; index++) {
            strJ[index] = str[index];
        }

        for (int index = 0; index < strJ.length; index++) {
            System.out.println(strJ[index]);
        }

        System.out.println(list);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(strJ));
        jComboBox1.addActionListener(this);
        
        btnNewButton_1 = new JButton("Go back");
        btnNewButton_1.setAction(action);
        btnNewButton_1.addActionListener(new ActionListener() {
        

			public void actionPerformed(ActionEvent e) {
        		
        		StartAMatch3 obn2 = new StartAMatch3();
                obn2.startmatch();
               dispose();
                
        	}
        	
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(75)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btnNewButton_1)
        					.addGap(60))
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        			.addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(43)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNewButton_1))
        			.addPreferredGap(ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
        			.addGap(46))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    public void formWindowOpened(java.awt.event.WindowEvent evt) {
        // addSqlDataToTable();

    }

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {

    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */

    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>

    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new NewTable().setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
 //   private final Action action = new SwingAction();
    private JButton btnNewButton_1;
    private final Action action = new SwingAction();

    // End of variables declaration
    @Override
    public void actionPerformed(ActionEvent e) {

        for (int i = 0; i < list.size(); i++) {
            if (i % 2 == 0) {
                if (jComboBox1.getSelectedItem().equals(list.get(i))) {
                    System.out.println(list.get(i) + " selected");
                    addSqlDataToTable(list.get(i));
                }
            }
        }
        // if (jComboBox1.getSelectedItem().equals(list.get(0))){
        // System.out.println(list.get(0) +" selected");
        // addSqlDataToTable(list.get(0));
        // }
        // if (jComboBox1.getSelectedItem().equals(list.get(2))){
        // System.out.println(list.get(2) +" selected");
        // addSqlDataToTable(list.get(2));
        // }
        // if (jComboBox1.getSelectedItem().equals(list.get(4))){
        // System.out.println(list.get(4) +" selected");
        // addSqlDataToTable(list.get(4));
        // }

    }
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "SwingAction");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
		}
	}
}